// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://idvwuzepcvzgnylafpow.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlkdnd1emVwY3Z6Z255bGFmcG93Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwNjExOTcsImV4cCI6MjA2NTYzNzE5N30.3dfQw7zxLP-ZB4EnWPtiec7ZIHFcoUOvYeY1dA28IYs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);